pipeline {
    agent any 
	triggers {
		pollSCM 'H/1 * * * *'
	}
	environment {
		CONFIG = 'Release'
		PLATFORM = 'Any CPU'
		AZURE_EMULATOR_HOME='C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator'
	}
    stages {
        stage('Stage - Start') {
            steps {
                echo 'Pipeline started' 
				echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
		stage('Check Env Vars') {
			steps {
				bat 'echo "Checking AZURE_EMULATOR_HOME:"'
				bat 'echo "%AZURE_EMULATOR_HOME%"'
			}
		}
		stage('Restore Nuget') {
			steps {
				bat 'dotnet restore Fineo\\Fineo.sln'
			}
		}
		stage('Sonar - Begin') {
			steps {
				bat 'dotnet sonarscanner begin /k:"f1ca19af842666e8987576d7a1100075bf1ed8b8" /n:"Fineo-Local" /v:"1.0" /d:sonar.login="f1ca19af842666e8987576d7a1100075bf1ed8b8" /d:sonar.exclusions="**/wwwroot/**,**/obj/**,**/bin/**" /d:sonar.cs.opencover.reportsPaths="**\\coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="**\\TestResults.trx"'
			}
		}
		stage('Build') {
			steps {
				bat "\"${tool 'MSBuild-MSVS2019'}\" ${WORKSPACE}\\Fineo\\Fineo.sln /p:Configuration=${env.CONFIG} /p:Platform=\"${env.PLATFORM}\" /p:ProductionVersion=1.0.0.${env.BUILD_NUMBER}"
			}
		}
		stage('Running Tests') {
			steps {
				parallel {
					a: {
						bat 'dotnet test Fineo\\Tests\\Test.AzureEmulatorHelper\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
						bat 'dotnet test Fineo\\Tests\\Test.FileStorage.AzreBlob\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
						bat 'dotnet test Fineo\\Tests\\Test.Fineo.Common\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
					}	
					b: {
						bat 'dotnet test Fineo\\Tests\\Test.Fineo.Interfaces\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
						bat 'dotnet test Fineo\\Tests\\Test.Fineo.SEC.Api\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
						bat 'dotnet test Fineo\\Tests\\Test.MessageBus.Azure\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
					}
				}
			}
		}
		stage('Sonar - End') {
			steps {
				bat 'dotnet sonarscanner end /d:sonar.login="f1ca19af842666e8987576d7a1100075bf1ed8b8"'
			}
		}
		stage('Deploy confirm') {
			steps {
				timeout(time: 15, unit: "MINUTES") {
					input message: 'Do you want to approve the deploy in production?', ok: 'Yes'
				}
			}
		}
		stage('Deploy') {
			steps {
				bat 'echo \"Deployed\"'
			}
		}
		
    }
}