pipeline {
    agent any 
	environment {
		CONFIG = 'Release'
		PLATFORM = 'Any CPU'
		BUILD_NUMBER = '101'
		AZURE_EMULATOR_HOME='C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator'
	}
    stages {
        stage('Stage - Start') {
            steps {
                echo 'Pipeline started' 
            }
        }
		stage('Check Env Vars') {
			steps {
				bat 'echo "Checking AZURE_EMULATOR_HOME:"'
				bat 'echo "%AZURE_EMULATOR_HOME%"'
			}
		}
		stage('Restore Nuget') {
			steps {
				bat 'dotnet restore Fineo\\Fineo.sln'
			}
		}
		stage('Sonar - Begin') {
			steps {
				bat 'dotnet sonarscanner begin /k:"f1ca19af842666e8987576d7a1100075bf1ed8b8" /n:"Fineo-Local" /v:"1.0" /d:sonar.login="f1ca19af842666e8987576d7a1100075bf1ed8b8" /d:sonar.exclusions="**/wwwroot/**,**/obj/**,**/bin/**" /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="**\TestResults.trx"
'
			}
		}
		stage('Build') {
			steps {
				bat "\"${tool 'MSBuild-MSVS2019'}\" ${WORKSPACE}\\Fineo\\Fineo.sln /p:Configuration=${env.CONFIG} /p:Platform=\"${env.PLATFORM}\" /p:ProductionVersion=1.0.0.${env.BUILD_NUMBER}"
			}
		}
		stage('Running Tests') {
			steps {
				bat 'dotnet test Fineo\\Tests\\Test.AzureEmulatorHelper\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
				bat 'dotnet test Fineo\\Tests\\Test.FileStorage.AzreBlob\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
				bat 'dotnet test Fineo\\Tests\\Test.Fineo.Common\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
				bat 'dotnet test Fineo\\Tests\\Test.Fineo.Interfaces\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
				bat 'dotnet test Fineo\\Tests\\Test.Fineo.SEC.Api\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
				bat 'dotnet test Fineo\\Tests\\Test.MessageBus.Azure\\ --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
			}
		}
		
    }
}